### ISSUE TITLE
Bug: v1.7.x onwards not recognised by Magic Earth

### ISSUE THREAD

**Issue by JonnyTech** [RHVoice/RHVoice#458]
The Magic Earth navigation app does not recognise RHVoice v1.7.x as a TTS voice provider.

Screenshots using v1.6.0

![160about](https://user-images.githubusercontent.com/3584732/152085657-85da4a5b-fdc6-4444-a165-79946e8bab00.png)
![160tts](https://user-images.githubusercontent.com/3584732/152085681-2569a34e-ac6f-4311-9b99-7b3b8641e00a.png)
![160me](https://user-images.githubusercontent.com/3584732/152085695-26a4de3c-b3ed-4d7e-b704-f17f164066b4.png)
![160melist](https://user-images.githubusercontent.com/3584732/152085713-2cc5c127-b74f-416e-8fd0-6352608756ec.png)

Screenshots using v1.7.9

![179about](https://user-images.githubusercontent.com/3584732/152085746-6d6425fd-d5a2-4711-8753-aa1963cd1efc.png)
![170tts](https://user-images.githubusercontent.com/3584732/152085761-54ad2316-711a-4325-bed4-3f7cb5329f25.png)
![179meset](https://user-images.githubusercontent.com/3584732/152086143-3562c60c-871a-4d38-8cd4-4cd655234034.png)
![179me](https://user-images.githubusercontent.com/3584732/152085786-a4f48749-8198-4879-93d3-2ef543a70d73.png)

Tested with AOSP 11.

Other apps seem to work well with both versions.

**Comment by JonnyTech** [comment]
[Version v1.8.0](https://github.com/RHVoice/RHVoice/discussions/543) also does not work with Magic Earth - is there a workaround available?

**Comment by pm4rcin** [comment]
Hi, looks like the last version that Magic Earth supports is RHVoice 1.6.0 so it's a regression somewhere. It shouldn't be hard to bisect the commit because between 1.6.0 and your report there are less than 20 commits. @JonnyTech do you use the fdroid or play store version? I use f-droid btw.

**Comment by zstanecic** [comment]
What is actually magic earth? How this thing works?

**Comment by zstanecic** [comment]
Ah, there was no question.
Why you post the screenshots?
We need an accessible way to reproduce this. 
Some logcat or something else, otherwise it cannot be resolved.

**Comment by pm4rcin** [comment]
> 

It's proprietary [navigation app](https://www.magicearth.com/) that uses OSM and regarding TTS it just uses default system provider. I've even e-mailed them about that problem because I thought they have hard-coded providers but looks like it's not the case. I don't know if we can debug it somehow. If you could provide some help I can send logs.

**Comment by pm4rcin** [comment]
Here's the [logcat](https://gist.github.com/pm4rcin/a2115de72885528bc0109d96c8dae0cb) of version 1.8

**Comment by pm4rcin** [comment]
Hi, so actually it's on Magic Earth's side. I have contacted them and they managed to reproduce and fix the problem and told me that it will be available with next update.

**Comment by zstanecic** [comment]
Hi,

In that case, it can be closed.

**Comment by pm4rcin** [comment]
@zstanecic so from me contacting them further it looks like RHVoice is the problem here. I'll quote a few things from e-mail so you could better understand.
"(...)it seems that RHVoice does not set country ISO codes for languages(...) you can kindly tell them to supply country codes for languages (not just language code).

e.g. for language "en", set locale "US"

I hope you understand where the problem lies. Please reopen issue. I'm using version 1.8.0 since it's the newest available in f-droid.
