### ISSUE TITLE
My impression about RHVoice 

### ISSUE THREAD

**Issue by NiKola-UE** [RHVoice/RHVoice#865]
I like the Android version, but it's a shame that those additional options are not available in Windows. A version for F-Droid also exists but is not updated. It doesn't seem to me to be compatible with Jieshuo, a lesser known Chinese screen reader that has been banned from Play Store. Here is an abridged excerpt from a private message I personally sent to Zvonimir. In it, I am currently dealing with the only female voice for Serbian named Dragana, but it can certainly apply to other languages ​​as well.

It's a shame that he pronounces so few English words, abbreviations, ordinal and Roman numerals correctly, but I believe that this will improve over time. Also, he accents some words incorrectly, the pause after the punctuation marks, especially after the period, - that is, between sentences - should be longer, and at least to me, the speech seems somehow more "natural" when the voice pitch is lowered in the settings. But I like how it accents words followed by a question mark or an exclamation mark. Later, there will certainly be numerous improvements, such as better coping with foreign languages (so not only with English), and the possibility of reading our words without diacritical marks as they are pronounced; which is a challenge and more difficult. As RHVoice as a program progresses further, it may be possible to combine different voices for their languages by setting a corresponding voice for each of the available languages, as already exists in Vocalizer.

Of course, these are just my impressions that you don't have to agree with, and don't take this as a disparagement or disrespect for someone's work. Far from the fact that I can blame you for anything, because I know very well that you did everything yourself and without any means, investing a lot in this.

I hope that soon we will be introduced to some more voices with different intonations and pronunciations, as much as possible.

**Comment by zstanecic** [comment]
Hi nikola,
Let answer you on your message bit by bit.
I like the Android version, but it's a shame that those additional options are not available in Windows. 
Which additional options? Can you be more specific?
A version for F-Droid also exists but is not updated. 
It is updated. Somebody from the community started to do it. I am not in charge of Fdroid.
It doesn't seem to me to be compatible with Jieshuo, a lesser known Chinese screen reader that has been banned from Play Store. 
RHVoice is compatible with jieshuo. I am using it all the time with it, Maybe it is a problem with your particular device?
Here is an abridged excerpt from a private message I personally sent to Zvonimir. 
Unfortunatelly, I haven't got any private message from you regarding Dragana. Please write at the address rhvoiceslavic(at)gmail dot com.
In it, I am currently dealing with the only female voice for Serbian named Dragana, but it can certainly apply to other languages ​​as well.
We are talking about serbian.
It's a shame that he pronounces so few English words, abbreviations, ordinal and Roman numerals correctly, but I believe that this will improve over time. 
She pronounces the common used words, and it will pronounce just these, because if we add more english pronounciations, we can make conflicts with for example, serbian words without diacritics. Case in the plural form cam easily become kejs. 
Also, he accents some words incorrectly, 
List please! Send it to the e-mail above. We are improving dictionary.
the pause after the punctuation marks, especially after the period, - that is, between sentences - should be longer, and at least to me, the speech seems somehow more "natural" when the voice pitch is lowered in the settings. 
I cannot say anything about pauses right now. There are mixed feelings in the community. Some people like pauses which we have now, some want an adjustable setting of pauses .
But I like how it accents words followed by a question mark or an exclamation mark. Later, there will certainly be numerous improvements, such as better coping with foreign languages (so not only with English), and the possibility of reading our words without diacritical marks as they are pronounced; which is a challenge and more difficult. 
We are not going to be like one of the serbian engines which has this text without diacritics predictor. This predictor had bugs and there will not be a good text without diacritics predictor. Coping with foreign words? We have automatic language switching inside RHVoice, which works between two different languages, written with two different scripts, i.e devanagari and latin, cyrillic and latin. 
As RHVoice as a program progresses further, it may be possible to combine different voices for their languages by setting a corresponding voice for each of the available languages, as already exists in Vocalizer.
You can set the voice for any of the language you use in the RHVoice settings in android.
Of course, these are just my impressions that you don't have to agree with, and don't take this as a disparagement or disrespect for someone's work. Far from the fact that I can blame you for anything, because I know very well that you did everything yourself and without any means, investing a lot in this.
I don't feel it line you said above. Thank you for your suggestions.
I hope that soon we will be introduced to some more voices with different intonations and pronunciations, as much as possible.
If somebody has a equipment and wants to do it, i can work with somebody to record new voices.

**Comment by NiKola-UE** [comment]
Hi, Zvonimir. 






Thank you for the detailed answer. Forgive me for my bad English - although I think you will surely understand what I am trying to say. 

By options that are missing in Windows, I mean switching from one language to another and their mutual synchronization and combining, as it already exists in Android. 


As for pauses after commas and periods, ie. between sentences , I think it should allow users to set as they please when possible. 



Dragana doesn't spell abbreviations very well because, for example, she doesn't pronounce RTS as "ER-Te-ES" or HRT as "Ha-Er-Te", but that's not that important. 

Reading texts without our diacrytic letters is possible in a commercial AnReader in Windows and AlfaNum TTS in Android, that are technically good despite all the shortcomings, but we know very well who is behind it, how it operates and that not everyone who needs it can have it. 

I sent you a message from my new address 
ni-kola.ue@outlook.com 
on 17.01. this year, where I was a little more detailed, mentioned Vesna, a voice you're also working on and explained why I didn't send you any recordings even though I promised. Check that it didn't end up in your spam folder, unless I made a typo or if you use a different address for this purpose. 



Note: I also created a issue on Newfon Speech Synthesizer's "Issues" page.

**Comment by zstanecic** [comment]
Hi, Zvonimir.
Hi, Nikola!
Thank you for the detailed answer. Forgive me for my bad English - although I think you will surely understand what I am trying to say.
Yes i understand you very well, although english i not my native language, too.
By options that are missing in Windows, I mean switching from one language to another and their mutual synchronization and combining, as it already exists in Android.
This option exists in Windows, and it is possible to accomplish this by editing the configuration file. 
I used the older version of the Jieshuo because I have some problems with latest.
In latest version there is a way to use Dragana on any device. Bugs are coming from jieshuo.
As for pauses after commas and periods, ie. between sentences , I think it should allow users to set as they please when possible.
It is not up to me, but on the developers of the core.
Dragana doesn't spell abbreviations very well because, for example, she doesn't pronounce RTS as "ER-Te-ES" or HRT as "Ha-Er-Te", but that's not that important.
This is tunable by dictionary. 
Reading texts without our diacrytic letters is possible in a commercial AnReader in Windows and AlfaNum TTS in Android, that are technically good despite all the shortcomings, but we know very well who is behind it, how it operates and that not everyone who needs it can have it.
AnRader is not a topic of this discussion, neither AnReader and RHVoice cannot be compared in any way.
I sent you a message from my new address
ni-kola.ue@outlook.com
on 17.01. this year, where I was a little more detailed, mentioned Vesna, a voice you're also working on and explained why I didn't send you any recordings even though I promised. Check that it didn't end up in your spam folder, unless I made a typo or if you use a different address for this purpose.
I haven't got any e-mail on 17.01 on my addres. I mentioned a new addres in the premium comment. See above
Note: I also created a issue on Newfon Speech Synthesizer's "Issues" page.
Please separate the topics! Newfon is not related to this discusion.

**Comment by NiKola-UE** [comment]
Well, very good! I like your precise answers. 


Yes, bugs are missing in Jieshuo, and that's what I meant, but it's a problem for the this app. On the other hand, some voices that are available for Windows are not available for Android (eg. Macedonian female voice Suze). 


Where exactly are the configuration files and dictionaries of RHVoice in Windows and how can they be edited? 

I mentioned AnReader only because of that missing option in RhVoice, but it goes without saying that we won't discuss it here. 

I sent a private message to the address zvonimirek222@yandex.com, but I don't know if it would be wise to send it to the address you provided because it is more personal; if you understand what I mean. 

And I also mentioned Newfon only because I know that you participate in the development of that project, and there is still no answer. Of course, I won't write about that here anymore.

**Comment by zstanecic** [comment]
Well, very good! I like your precise answers.

Yes, bugs are missing in Jieshuo, and that's what I meant, but it's a problem for the this app. On the other hand, some voices that are available for Windows are not available for Android (eg. Macedonian female voice Suze).
Macedonian voice suze is not a topic of this discussion. What are you trying to achieve?
Where exactly are the configuration files and dictionaries of RHVoice in Windows and how can they be edited?
I don't want to answer here to unrelated questions. Please close this issue and switch to private communication in our native language..
I mentioned AnReader only because of that missing option in RhVoice, but it goes without saying that we won't discuss it here.
I sent a private message to the address zvonimirek222@yandex.com, but I don't know if it would be wise to send it to the address you provided because it is more personal; if you understand what I mean.
No, i don't understand. i gave an e-mail to which you can send RHVoice related questions.
And I also mentioned Newfon only because I know that you participate in the development of that project, and there is still no answer. Of course, I won't write about that here anymore.
Newfon was part of my development journey some time back just for fun, to see can we add, one Man from russia along with me a pseudoserbian or croatian support.

**Comment by NiKola-UE** [comment]
I opened this issue as my general review of RHVoice, although I referred to the part from the email that fits perfectly and I noticed that not all voices are equally represented on all platforms. By configuration files and dictionaries, I meant what you said: "this option exists in Windows, and it is possible to accomplish this by editing the configuration file." So, it seemed to me that there are some parameters that can be changed at will. If I'm wrong, what exactly do you mean? 

I don't know why my email didn't arrive, unless there is some kind of censorship or blocking between Microsoft and Yandex or something like that. I can send you another message if necessary, although I don't know if it will arrive. If it doesn't arrive again, I should try at zvonimir.stanecic4@gmail.com if it's still active, but well. However, I have more or less already repeated everything I said there, so I don't think there is any need to repeat it again. As I said, there I also mentioned voice Vesna, which she told me earlier was in the works, and the reasons why I didn't send you the promised recordings, but which are of a private nature, so I don't think it's wise to share them here. 



You can close this issue if you think we've said about everything we needed to. There are already many open issues and discussions anyway.

**Comment by zstanecic** [comment]
I cannot close it myself. Please close it as you were a creator the issue. We can continue by email

And I will answer you regarding configs.

**Comment by NiKola-UE** [comment]
I remembered to add a few more things, so I'll close this issue after your answer. 


As it already exists on Android, a so called RHVoice's client application for Windows would be welcome, which would have settings that are not available in screen readers, and which would suit both beginners who are looking for simplicity, and advanced users for whom there would be additional settings. Automatic updates would be desirable. 

I also notice that the RHVoice addons for NVDA are not present in the Addon Store, so they have to be installed manually from external links. 

As for Dragana, I think her voice fits better with the Chakavian dialect, but that's just my observation. Digression: Macedonian voices read Serbian Cyrillic well and I prefer the pause with them, but they don't recognize all the letters. Of course, one written word in different languages has completely opposite meanings, but this can be compensated to some extent by more accurate and precise detection and recognition of language and context, which you as a linguist know and understand much better than I do. 

The more voices, colors and parameters, the better, but harder, more complex and complicated. Someone prefers a stronger and more dynamic voice, someone more dream and calm; some want a voice that corresponds to the standard language, some to the local dialect and promounciation; someone wants an radio or TV narrator's and serious voice, someone like the one they hear in everyday speech, etc. Adding modulations and inflections that are already in the ESpeak and Newfon can improve things a lot, but it's harder to do when using natural voice samples. 







Finally, check again if the message I sent you ended up in spam or trash / junk. If not, no important

**Comment by zstanecic** [comment]
Hi Nikola,

No, my message has not ended in the spam /junk folder. 

Although we are under a gpl license when it comes to NVDA driver, i don't know i sit possible for such things.

Note, addon is under gplV3. 

I cannot answer more, as i don't have infos.



-- 
Ta wiadomość e-mail została sprawdzona pod kątem wirusów przez oprogramowanie antywirusowe Avast.
www.avast.com

**Comment by NiKola-UE** [comment]
It's okay, I understood everything. It's not clear to me why some voices are downloaded directly from the site, and some from the Loader Page, but all of that can be written in the instruction manual and user guide, as well as everything we've talked about here. Of course, you don't need to do all that yourself, but whoever, how and as much as they can. Fortunately, the RHVoice community is expanding and growing more and more. 

Now you have my new email address, which you can freely forward to whoever you want, so you and your colleagues can also inform me about further steps and development. Censorship is the only explanation I can think of for the message. Obviously, something is wrong because I was properly notified that the message arrived, while you didn't, but that's fine - there are other ways. 


I certainly undertake to fulfill my promise in regard to sending the recordings although I am currently prevented from doing so for the reasons I stated in the message early and which I am transcribing here, although I do not think it is wise for me to do so. 





"I am sincerely sorry that I did not send you any recordings, even though I promised to do so, but I simply could not find a suitable room or equipment; therefore, I do not have the conditions to record something that must be worked on very carefully, dedicatedly and seriously. Here in Užice I only know of one professional studio (not sure if it's still in business) but I have no idea how much it might cost me, considering I'm unemployed and doing nothing, which of course is my problem. 



In any case, if I manage to make at least a few good and high-quality mono recordings in WAVE format with a sample rate of 48 KHZ, I will send them immediately, but even against my will, I cannot promise you anything for the reasons mentioned." 

> 




Greetings to all and all the best.
